### PR TITLE
Recommendations info dialog

### PR DESCRIPTION
**Pull request by eoji**
# what 
Showing recommendations info, with tests (•̀ᴗ•́)و ̑̑

# how
Updated strings.
Added the new info icon.
On user click, we show the alert.
Test ✨

# why
GIF

# c-c-c-check it out

cc @dannyalright

### CODE REVIEW

**Comment by dannyalright** [comment]
minor thing: I'd expect the _Got it._ to be all caps on Android.

1. would you, too?
2. is this consistent with how we label dialog buttons elsewhere on the app?

**Comment by eoji** [comment]
@dannyalright 
1. I actually would expect it to be in caps, per https://material.io/design/components/dialogs.html#alert-dialog
2. Yes, our other dialog buttons have sentence case 🤔

**Comment by dannyalright** [comment]
cool. I'd prefer it to be _GOT IT_, without the period at the end. Should we do it here, one-off, and I'll make a card to fix others another time? Or just keep as is and do all at another time?

**Comment by eoji** [comment]
@dannyalright Let's do it now and I'll open a PR with that new string!

**Comment by eoji** [comment]
Here's the strings PR: https://github.com/kickstarter/kickstarter/pull/11028

**Comment by eoji** [comment]
New string 😎 @dannyalright

**Comment by dannyalright** [comment]
awesome, thank you!

**Comment by eoji** [comment]
[Recommendations and Privacy UI in Settings](https://trello.com/c/qr4OXlu1/606-recommendations-and-privacy-ui-in-settings)

**Pull request merged**
