### PR TITLE
[UI] Snackbar style update

### PR DESCRIPTION
**Pull request by eoji**
# What ❓
Removing rounded corners and margin from Snackbars because they were all forced to the bottom in API 28.

# Story 📖
[Update Snackbar Styles](https://trello.com/c/ZgWvg0ok/1151-update-snackbar-styles)

# B4 & After 👀

### CODE REVIEW

**Comment by eoji** [comment]
[Update Snackbar styles](https://trello.com/c/ZgWvg0ok/1151-update-snackbar-styles)

**Comment by dannyalright** [comment]
Given that we had to lose the bottom margin/inset and that we're now using API 28, I think we should slowly migrate this over to the [native Snackbar pattern](https://material.io/design/components/snackbars.html) (with our primary and accent colors).

Let me know if you want me to make a card for this, or if we should just add it to our design pairing @eoji.

**Comment by eoji** [comment]
Like left aligning them? Yeah, let's make a card. Let's actually make a giant API 28 theme card and everything we're updating to a list with checkboxes so we can keep track of the changes!

**Comment by dannyalright** [comment]
Nice. Added [here](https://trello.com/c/PtSIgPet/654-api-28-design-updates)

**Pull request merged**
