### PR TITLE
NT-1777:Refactor Picasso code due to integrate firebase in-app sdk

### PR DESCRIPTION
**Pull request by hadia**
# 📲 What

Change Picasso call in viewholder to Picasso.get()

# 🤔 Why

Integrating firebase in-app messaging sdk user higher version from Picasso lib

# 🛠 How
Change Picasso call in viewholder from Picasso.with(context) to Picasso.get()

# 👀 See
Screen Shot 2021-02-17 at 7 08 14 PM

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA
test all lists that have images to show

# Story 📖

https://kickstarter.atlassian.net/browse/NT-1777

### CODE REVIEW

**Review by leighdouglas — APPROVED** [review]
Lgtm once @Arkariang approves as well!

**Comment by Arkariang** [comment]
Probably this PR is not necessary, we need to update the feature branch with the lates master and that will do.

**Comment by Arkariang** [comment]
> Probably this PR is not necessary, we need to update the feature branch with the lates master and that will do.

as @hadia flagged to me Master is still on Java so we are gonna have conflicts either way, so go ahead and merge this PR 👍

**Review by Arkariang — APPROVED** [review]
LGTM! 
for future ocasions, you can update the feature branch with the latest master without doing a PR, that's ok with me 👍

**Pull request merged**
