### PR TITLE
NT-1163: Marketing Push Notification Cell UI

### PR DESCRIPTION
**Pull request by Arkariang**
# 📲 What

UI Adding new row under Notifications setting menu 
Before: left simulator
Designs: in between simulators
Now: Right simulator
Screen Shot 2020-04-30 at 12 56 46 PM

# 🤔 Why

It will be needed for toggling marketing notifications

# Story 📖

[Marketing Push Notification Cell UI](https://kickstarter.atlassian.net/browse/NT-1163)

### CODE REVIEW

**Comment by colleenmacd** [comment]
Hi @Arkariang sorry I realized after I approved this that there are things other than the marketing push cell that seem to have changed on this screen. Everything other than that last cell should remain the same as before -- looks like some of the cell backgrounds are missing?

I also apologize that i might have been working off an old/incorrect Figma file for this addition. I'll add this to the Jira ticket but here is what this screen actually looks like in the app: https://www.figma.com/file/BRwrViI0Vmh3vZE71oCPqg/Settings?node-id=1%3A3380

**Comment by Arkariang** [comment]
@colleenmacd Nw! updated now, take a look at the screenshoot in the description, in there you have the before and the new changes :)

**Comment by colleenmacd** [comment]
yay! looks great -- the only thing im wondering about is the unselected color of the email / phone icons. looks like they are supposed to be a light grey color, but they look black in the "Anouncements" cell

**Comment by eoji** [comment]
@colleenmacd the colors will get properly set when the API is all ready 🚀

**Comment by colleenmacd** [comment]
gotcha ok!

**Pull request merged**
