### PR TITLE
NT-2059: Update stripe sdk (payments) from 12.0.1 to 16.10.0

### PR DESCRIPTION
**Pull request by Arkariang**
# 📲 What

- Update stripe sdk from 12.0.1 to 16.10.0

# 🤔 Why
Screen Shot 2021-06-21 at 2 47 39 PM

- See https://github.com/stripe/stripe-android/blob/master/MIGRATING.md
- See https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md

# 🛠 How
- `Card` type from Stripe dependency is now internal and not accessible, substitute over `CardParams`
- `Token` constructor is now internal no longer available for testing
- [CardParams](https://github.com/stripe/stripe-android/blob/master/payments-core/src/main/java/com/stripe/android/model/CardParams.kt) internal variables for cards like `number`, `cvc`, `expMonth`, `expYear` no available as they were previously`. 
- Any validation related to those previously mentioned fields takes place on stipe end see [CardInputWidget](https://github.com/stripe/stripe-android/blob/9799aa052eddc01c457b4d6ee74a7dac6dabaed3/payments-core/src/main/java/com/stripe/android/view/CardInputWidget.kt#L219)
- Remove any use for the deprecated class [CardUtils](https://github.com/stripe/stripe-android/blob/master/payments-core/src/main/java/com/stripe/android/CardUtils.kt)

# 👀 See
- Trying to pay in a non USA project, the not available payment methods are disabled
Screen Shot 2021-06-21 at 1 08 00 PM
- Successfully pledge to a project
- Successfully update a pledge
- Successfully change your payment method
- Successfully change the reward tier
- Successfully use 3DS visa cards to make a payment

|  |  |

# 📋 QA
- Add new payment method, from settings -> account -> payment methods
- Add new payment method, from pledge screen -> new payment method
- make sure you can add all the supported card types `AMERICAN_EXPRESS,DINERS_CLUB,DISCOVER,JCB,MASTERCARD,UNIONPAY,VISA`, here you can see tes cards for all of those types. [Stripe Test Cards](https://stripe.com/docs/testing#cards)
- make sure you can do payments with any of the previous type of payments 
- make sure you can do payments with the 3DS visa types, here some flow samples and test cards https://kickstarter.atlassian.net/wiki/spaces/PAYM/pages/1083671123/Known+UI+issues
- make sure if you pledge to a non USA project you cannot use any of these payment methods: `DINERS_CLUB,DISCOVER,JCB,UNIONPAY,`
- Successfully pledge to a project
- Successfully update a pledge
- Successfully change your payment method
- Successfully change the reward tier

# Story 📖
[NT-2059](https://kickstarter.atlassian.net/browse/NT-2059)

### CODE REVIEW

**Comment by jgsamudio** [comment]
Going to manage pledge, and selecting to change your payment method does not allow the user to change their credit card. The button is still disabled when they switch the card. When I pledged, I added a new mastercard and used that to pledge

Screen Shot 2021-06-21 at 1 08 00 PM

**Comment by jgsamudio** [comment]
Pledging with this 3DS card: 4000002500003155 results in a crash. 
https://stripe.com/docs/testing#regulatory-cards

Crash log:
```
2021-06-23 10:21:26.319 13795-13795/com.kickstarter.kickstarter.internal.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kickstarter.kickstarter.internal.debug, PID: 13795
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kickstarter.kickstarter.internal.debug/com.stripe.android.view.PaymentAuthWebViewActivity}: java.lang.IllegalStateException: PaymentConfiguration was not initialized. Call PaymentConfiguration.init().
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: PaymentConfiguration was not initialized. Call PaymentConfiguration.init().
        at com.stripe.android.PaymentConfiguration$Companion.loadInstance(PaymentConfiguration.kt:74)
        at com.stripe.android.PaymentConfiguration$Companion.getInstance(PaymentConfiguration.kt:66)
        at com.stripe.android.view.PaymentAuthWebViewActivityViewModel$Factory.create(PaymentAuthWebViewActivityViewModel.kt:120)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.stripe.android.view.PaymentAuthWebViewActivity.getViewModel(Unknown Source:2)
        at com.stripe.android.view.PaymentAuthWebViewActivity.customizeToolbar(PaymentAuthWebViewActivity.kt:172)
        at com.stripe.android.view.PaymentAuthWebViewActivity.onCreate(PaymentAuthWebViewActivity.kt:65)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Review by jgsamudio — COMMENTED** [review]
The code looks good! Only issues are the comments above

**Review by leighdouglas — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
