### PR TITLE
NT-1787:Refactor VideoActivity

### PR DESCRIPTION
**Pull request by hadia**
# 📲 What

Remove butter knife from VideoActivity and replaced with view binding

# 🤔 Why

deprecated butterknife

# 🛠 How

1- change VideoActivity from java to kotlin
2-remove butter-knife and replace it with viewbinding

# 👀 See

https://user-images.githubusercontent.com/1075310/108737838-a95e9380-753b-11eb-8a2c-7b18733a2739.mp4

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA

# Story 📖
https://kickstarter.atlassian.net/browse/NT-1787

### CODE REVIEW

**Comment by Arkariang** [comment]
Should this PR be renamed to Refactor VideoActivity?

**Comment by hadia** [comment]
> Should this PR be renamed to Refactor VideoActivity?

Done

**Review by Arkariang — APPROVED** [review]
lgtm! Tested it on my environment playing the video and using the controls as well (play/pause/skip)

https://user-images.githubusercontent.com/4083656/108895659-bd040b80-75c8-11eb-86e1-0121f69f42df.mp4

**Review by leighdouglas — APPROVED** [review]
LGTM! Tested video playback on my device and it works great 🎉

**Pull request merged**
