### PR TITLE
EP-251 : Page Viewed (manage_pledge)

### PR DESCRIPTION
**Pull request by sunday-okpoluaefe**
# 📲 What

Android: Page Viewed (manage_pledge)

# 🤔 Why

Segment Implementation 

# 🛠 How

- Created new method ``` trackManagePledgePageViewed ``` in ``` AnalyticEvents ``` class

``` 
 /**
     * Sends data associated with page view event to the client.
     *
     * @param pledgeData: The selected pledge data.
     */
    fun trackManagePledgePageViewed(pledgeData: PledgeData) {
        val props: HashMap<String, Any> = hashMapOf(CONTEXT_PAGE.contextName to MANAGE_PLEDGE.contextName)
        props.putAll(AnalyticEventsUtils.pledgeDataProperties(pledgeData, client.loggedInUser()))
        client.track(PAGE_VIEWED.eventName, props)
    }

```

- Called method on ``` BackingFragment ``` page expanded
```
  projectDataAndBackedReward
                    .compose(takeWhen<Pair<ProjectData, Reward>, Void>(this.nativeProjectActionButtonClicked))
                    .filter { ObjectUtils.isNotNull(it) }
                    .filter { it.first.project().isLive && it.first.project().isBacking }
                    .map { pledgeData(it.second, it.first, PledgeFlowContext.MANAGE_REWARD) }
                    .compose(bindToLifecycle())
                    .subscribe(this.lake::trackManagePledgePageViewed)
```

# 👀 See

Screenshot 2021-03-08 at 16 39 25

Screenshot 2021-03-16 at 11 01 16

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA

- On the profile page, select from the list of backed projects.
- Click on the ``` manage ``` button. You should see the new event registered on the segment console

Screenshot 2021-03-16 at 11 00 59

# Story 📖

https://kickstarter.atlassian.net/browse/EP-251

### CODE REVIEW

**Review by Arkariang — CHANGES_REQUESTED** [review]
Add tests to check the analytic event has been triggered, `ProjectViewModelTest` holds all the unit tests for this ViewModel

**Comment by sunday-okpoluaefe** [comment]
> Add tests to check the analytic event has been triggered, `ProjectViewModelTest` holds all the unit tests for this ViewModel

Done

**Review by Arkariang — APPROVED** [review]
lgtm, update the branch with the latest master and is good to go 👍

**Comment by sunday-okpoluaefe** [comment]
This has been closed and the ticket moved to TO-DO until further information is provided

**Pull request closed without merging**
