### PR TITLE
Fix to use doAfterTerminate instead of finallyDo.

### PR DESCRIPTION
**Pull request by hotchemi**
### Overview

- Just Fix to use `doAfterTerminate` instead of `finallyDo` since `finallyDo` is deprecated already.

### CODE REVIEW

**Comment by hotchemi** [comment]
@luoser Any update?

**Comment by ttkla523** [comment]
Sorry, I'm learning programming. Too excited, wrong operation, Very Sorry!!!

**Comment by luoser** [comment]
thanks for updating!

**Comment by hotchemi** [comment]
Thx!

**Pull request merged**
