### PR TITLE
Login Tout & Sign Up, GDPR style

### PR DESCRIPTION
**Pull request by eoji**
# what
Updating the strings from the server.
Removing Facebook copy.
Updating the disclaimer.

# why
|￣￣￣￣￣￣|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;G&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
| ＿＿＿＿＿__| 
(\ _ /)  || 
(•ㅅ•) || 
/ 　 づ 

# see
 

cc @dannyalright @nnekab

### CODE REVIEW

**Comment by eoji** [comment]
[Create New w Email Account Copy](https://trello.com/c/MFgu6F45/640-create-new-w-email-account-copy)

**Comment by dannyalright** [comment]
does this PR also affect the sign-up screen, like iOS?

**Comment by eoji** [comment]
@dannyalright also the facebook confirmation page

**Comment by eoji** [comment]
[Newsletter Consent Copy](https://trello.com/c/EGdFRLrB/635-newsletter-consent-copy)

**Comment by ifbarrera** [comment]
@dannyalright @eoji yep, affects all three on iOS as well. So much text 😓

**Comment by eoji** [comment]
@dannyalright added the sign up screenshot!

**Comment by eoji** [comment]
One more screenshot @dannyalright

**Comment by eoji** [comment]
[Newsletter Consent Copy Android](https://trello.com/c/unOX55mo/641-newsletter-consent-copy-android)

**Comment by eoji** [comment]
[Create New w Email Account Copy - Android](https://trello.com/c/ysDGzJVY/634-create-new-w-email-account-copy-android)

**Pull request merged**
